### ISSUE TITLE
Assign_profiles() has errors 

### ISSUE THREAD

**Issue by ZEROBRS** [SECOORA/GUTILS#6]
I found two bugs in the GUTILS assign_profile() function.
For line 77 in assign_profiles.
inflections = np.where(np.diff(delta_depth) != 0)[0]
https://github.com/SECOORA/GUTILS/blob/087967888cb037bd7166c51af65b464052aba8b5/gutils/yo.py#L77
This line will think each extreme point is a new profiles.
							128 129  130 131
For example, delta_depth = [ .., .., 1.0, 0.0, -1.0, -1.0, …..], then
inflections will be [0, 128, 129, 200, ….]. For 128 ~129 is a little profile for extreme point, that will looks like the graph below. 
￼
<img width="633" alt="screen shot 2018-03-12 at 9 47 13 am" src="https://user-images.githubusercontent.com/11727156/37286818-dea53f0a-25e1-11e8-89e3-ea27f3f1c5b8.png">

and I guess the sampling algorithm, between line 57-66 you get sampling data depending on the time interval(tsint), which cases the offset issues in the graph below
<img width="632" alt="screen shot 2018-03-12 at 9 51 25 am" src="https://user-images.githubusercontent.com/11727156/37286855-f5a4e1ec-25e1-11e8-9ead-62c5d5fc75c8.png">
I think sampling data can find extreme points, but can’t get a very precisely extreme point.

**Comment by xiangling1994** [comment]
<img width="168" alt="screen shot 2018-03-12 at 10 43 44 am" src="https://user-images.githubusercontent.com/11727156/37286970-4795758e-25e2-11e8-89d1-0f8257cc120a.png">
My example should looks like this, my format looks mess up.

**Comment by xiangling1994** [comment]
One of my ideas to fix this issue is readjust the profile id by merging the small profile piece and profile offset with previous profile. and I would add code right before assign_profiles return profile_df(https://github.com/SECOORA/GUTILS/blob/087967888cb037bd7166c51af65b464052aba8b5/gutils/yo.py#L123). Base my idea, i make a function to reassign the profile id base on the result i got from Gutils, I ran one test, the result showing In picture below, upper graph is the result without readjust profile id, and second one is the result with readjust profile id.
![screen shot 2018-03-07 at 9 35 38 am](https://user-images.githubusercontent.com/11727156/37292929-c2c8d7e2-25f0-11e8-82dc-9113fd163bfc.png)

So I make one function to read following points and return a flag. If there is a real curve(not false curve) coming, It will set flag as "curve coming". and assume every points before that curve was belong to one profile.
and this function will be called only when something weird happening, such as straight line has more than one profile or there is a curve exist inside the profile.
my idea is something like I make a assumption about slocum glider's direction(go up or down) first, base on direction i assign profile. If the points goes differently than my assumption, I will check the data, if it is ok i leave it alone, if it is wrong, i fix it.

**Comment by kwilcox** [comment]
@xiangling1994 thanks for the bug report. Would you be willing to throw together a test function that fails with your use case? I'd even take a CSV file that I could load into a `DataFrame` and pass to `assign_profiles`.

**Comment by xiangling1994** [comment]
@kwilcox Hi, you can download data, code and readme from this link: http://cercos.ocean.dal.ca/seafile/f/f6994e0c01/ . If you need anything else, just tell me, very happy to help.

**Comment by kwilcox** [comment]
@ZEROBRS Sorry for the delay. Looking at this today before making a GUTILS release.

**Comment by kwilcox** [comment]
@ZEROBRS I've got some changes that seem to be working, this is what your provided ASCII file looks like now after calling `assign_profiles`:

![download 2](https://user-images.githubusercontent.com/13939/48648298-d61abc80-e9bc-11e8-8369-b9bf25be6345.png)

**Comment by ZEROBRS** [comment]
This graph looks really good, can I ask which commit contains the change for this?

**Comment by kwilcox** [comment]
I noticed there are still extra profiles being identified at the extremes of the profiles when `tsint` is set low. I don't think there is a good way around this... the glider bounced a bit at the extremes of each profile. Any ideas?

`tsint: 4`: 
![tsint4](https://user-images.githubusercontent.com/13939/48711513-79e0b400-ebd9-11e8-9251-901dacaaf2cb.png)

`tsint: 2`:
![tsint2](https://user-images.githubusercontent.com/13939/48711517-7e0cd180-ebd9-11e8-83fb-a6c812e070ae.png)
